---
# Catalog DB Secret
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "retail-store.fullname" . }}-catalog-db
  namespace: {{ include "retail-store.namespace" . }}
  labels:
    {{- include "retail-store.catalog.labels" . | nindent 4 }}
type: Opaque
data:
  RETAIL_CATALOG_PERSISTENCE_USER: {{ .Values.catalog.app.persistence.secret.username | b64enc | quote }}
  RETAIL_CATALOG_PERSISTENCE_PASSWORD: {{ .Values.catalog.app.persistence.secret.password | b64enc | default (include "getOrGeneratePass" (dict "Namespace" (include "retail-store.namespace" .) "Kind" "Secret" "Name" (printf "%s-catalog-db" (include "retail-store.fullname" .)) "Key" "RETAIL_CATALOG_PERSISTENCE_PASSWORD")) | quote }}
---
# Orders DB Secret
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "retail-store.fullname" . }}-orders-db
  namespace: {{ include "retail-store.namespace" . }}
  labels:
    {{- include "retail-store.orders.labels" . | nindent 4 }}
type: Opaque
data:
  RETAIL_ORDERS_PERSISTENCE_USERNAME: {{ .Values.orders.app.persistence.secret.username | b64enc | quote }}
  RETAIL_ORDERS_PERSISTENCE_PASSWORD: {{ .Values.orders.app.persistence.secret.password | b64enc | default (include "getOrGeneratePass" (dict "Namespace" (include "retail-store.namespace" .) "Kind" "Secret" "Name" (printf "%s-orders-db" (include "retail-store.fullname" .)) "Key" "RETAIL_ORDERS_PERSISTENCE_PASSWORD")) | quote }}
---
# Orders RabbitMQ Secret
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "retail-store.fullname" . }}-orders-rabbitmq
  namespace: {{ include "retail-store.namespace" . }}
  labels:
    {{- include "retail-store.orders.labels" . | nindent 4 }}
type: Opaque
data:
  SPRING_RABBITMQ_USERNAME: {{ .Values.orders.app.messaging.rabbitmq.secret.username | b64enc | quote }}
  SPRING_RABBITMQ_PASSWORD: {{ .Values.orders.app.messaging.rabbitmq.secret.password | b64enc | default (include "getOrGeneratePass" (dict "Namespace" (include "retail-store.namespace" .) "Kind" "Secret" "Name" (printf "%s-orders-rabbitmq" (include "retail-store.fullname" .)) "Key" "SPRING_RABBITMQ_PASSWORD")) | quote }}
