apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "retail-store.fullname" . }}-ui
  namespace: {{ include "retail-store.namespace" . }}
  labels:
    {{- include "retail-store.ui.labels" . | nindent 4 }}
{{- with .Values.ui.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "retail-store.fullname" . }}-catalog
  namespace: {{ include "retail-store.namespace" . }}
  labels:
    {{- include "retail-store.catalog.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "retail-store.fullname" . }}-cart
  namespace: {{ include "retail-store.namespace" . }}
  labels:
    {{- include "retail-store.cart.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "retail-store.fullname" . }}-checkout
  namespace: {{ include "retail-store.namespace" . }}
  labels:
    {{- include "retail-store.checkout.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "retail-store.fullname" . }}-orders
  namespace: {{ include "retail-store.namespace" . }}
  labels:
    {{- include "retail-store.orders.labels" . | nindent 4 }}
