{{- if .Values.orders.postgresql.create }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "retail-store.fullname" . }}-orders-postgresql
  namespace: {{ include "retail-store.namespace" . }}
  labels:
    {{- include "retail-store.postgresql.labels" . | nindent 4 }}
spec:
  type: {{ .Values.orders.postgresql.service.type | quote }}
  ports:
    - port: {{ .Values.orders.postgresql.service.port }}
      targetPort: postgresql
      protocol: TCP
      name: postgresql
  selector:
    {{- include "retail-store.postgresql.selectorLabels" . | nindent 4 }}
{{- end }}
